language: csharp
mono: none
dotnet: 2.0.5
before_script:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./run-tests.sh
branches:
  only:
    - master
    - develop
    - testing
script:
  - ./travis-build.sh
  - ./run-tests.sh